/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.Dimension;
import javax.swing.JDesktopPane;

/**
 *
 * @author ASUS
 */
public class MDI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MDI.class.getName());
    public static JDesktopPane jDesktopPane_MDI;
    public MDI() {
        initComponents();
        this.setSize(new Dimension(1200,700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("SIGVET");
        
        this.setLayout(null);
        jDesktopPane_MDI=new JDesktopPane();
        
        int ancho=java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto=java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_MDI.setBounds(0,0,ancho,(alto-110));
        this.add(jDesktopPane_MDI);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu_proveedores = new javax.swing.JMenu();
        jMenuItem_nuevo_proveedor = new javax.swing.JMenuItem();
        jMenuItem_gestionar_proveedores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu_proveedores.setText("Proveedores");

        jMenuItem_nuevo_proveedor.setText("Nuevo Proveedor");
        jMenuItem_nuevo_proveedor.addActionListener(this::jMenuItem_nuevo_proveedorActionPerformed);
        jMenu_proveedores.add(jMenuItem_nuevo_proveedor);

        jMenuItem_gestionar_proveedores.setText("Gestionar Proveedores");
        jMenuItem_gestionar_proveedores.addActionListener(this::jMenuItem_gestionar_proveedoresActionPerformed);
        jMenu_proveedores.add(jMenuItem_gestionar_proveedores);

        jMenuBar1.add(jMenu_proveedores);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_nuevo_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_nuevo_proveedorActionPerformed
        // TODO add your handling code here:
        Vistas.FrmNuevoProveedor form = new Vistas.FrmNuevoProveedor();
        Modelos.Proveedor proveedor=new Modelos.Proveedor();
        Modelos.ProveedorDAO dao= new Modelos.ProveedorDAO();
        Controladores.CtrlProveedor.CtrlNuevoProveedor ctrl=new Controladores.CtrlProveedor.CtrlNuevoProveedor(proveedor, form, dao);
        
        jDesktopPane_MDI.add(form);
        form.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem_nuevo_proveedorActionPerformed

    private void jMenuItem_gestionar_proveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestionar_proveedoresActionPerformed
        // TODO add your handling code here:
        
        Vistas.FrmGestionarProveedores form = new Vistas.FrmGestionarProveedores();
        Modelos.Proveedor proveedor=new Modelos.Proveedor();
        Modelos.ProveedorDAO dao= new Modelos.ProveedorDAO();
        Controladores.CtrlProveedor.CtrlGestionarProveedores ctrl=new Controladores.CtrlProveedor.CtrlGestionarProveedores(proveedor, form, dao);
        
        ctrl.cargarTabla();
        jDesktopPane_MDI.add(form);
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItem_gestionar_proveedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MDI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_gestionar_proveedores;
    private javax.swing.JMenuItem jMenuItem_nuevo_proveedor;
    private javax.swing.JMenu jMenu_proveedores;
    // End of variables declaration//GEN-END:variables
}
